# Generated by Django 3.1.6 on 2021-02-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('civility', models.CharField(choices=[('MLL', 'Mlle'), ('MME', 'Mme'), ('MR', 'Mr')], default='MME', max_length=3, verbose_name='Civilité')),
                ('adress', models.CharField(max_length=200, verbose_name='Adresse')),
                ('phone', models.CharField(max_length=22, verbose_name='Téléphone')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='E-mail')),
                ('nationality', models.CharField(max_length=50, verbose_name='Nationalité')),
                ('birth_date', models.DateField(max_length=50, verbose_name='Date de naissance')),
                ('blood', models.CharField(choices=[('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('O-', 'O-'), ('O+', 'O+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3, verbose_name='Groupe sanguin')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('state', models.CharField(choices=[('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('O-', 'O-'), ('O+', 'O+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3, verbose_name='Etat')),
                ('note', models.TextField(blank=True, null=True)),
                ('dette', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
