# Generated by Django 3.1.6 on 2021-02-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0002_creneau_planning'),
        ('client', '0002_coach_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='creneau',
            field=models.ManyToManyField(to='creneau.Creneau', verbose_name='créneau'),
        ),
        migrations.AddField(
            model_name='coach',
            name='creneau',
            field=models.ManyToManyField(to='creneau.Creneau', verbose_name='créneau'),
        ),
    ]
