# Generated by Django 3.1.6 on 2021-02-16 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0003_auto_20210216_1534'),
        ('client', '0003_auto_20210216_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='creneau',
        ),
        migrations.AddField(
            model_name='client',
            name='creneau',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='creneau.creneau', verbose_name='créneau'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='coach',
            name='creneau',
        ),
        migrations.AddField(
            model_name='coach',
            name='creneau',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='creneau.creneau', verbose_name='créneau'),
            preserve_default=False,
        ),
    ]
