# Generated by Django 3.1.6 on 2021-02-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20210216_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(choices=[('A', 'Active'), ('S', 'Suspendue'), ('N', 'Non active')], max_length=3, verbose_name='Etat'),
        ),
    ]
