# Generated by Django 3.1.6 on 2021-02-18 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0003_auto_20210216_1534'),
        ('client', '0005_auto_20210218_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='creneau',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='creneau.creneau', verbose_name='créneau'),
        ),
    ]
