# Generated by Django 3.1.6 on 2021-03-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20210218_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.CharField(max_length=200),
        ),
    ]
