# Generated by Django 3.1.6 on 2021-03-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20210306_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
