# Generated by Django 3.1.6 on 2021-03-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20210306_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='slug',
        ),
    ]
