# Generated by Django 3.1.6 on 2021-03-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_remove_client_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='blood',
            field=models.CharField(blank=True, choices=[('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('O-', 'O-'), ('O+', 'O+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3, null=True, verbose_name='Groupe sanguin'),
        ),
        migrations.AlterField(
            model_name='client',
            name='civility',
            field=models.CharField(blank=True, choices=[('MLL', 'Mlle'), ('MME', 'Mme'), ('MR', 'Mr')], default='MME', max_length=3, null=True, verbose_name='Civilité'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('S', 'Suspendue'), ('N', 'Non active')], max_length=3, null=True, verbose_name='Etat'),
        ),
    ]
