# Generated by Django 3.1.6 on 2021-03-09 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0003_auto_20210216_1534'),
        ('client', '0011_auto_20210307_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='creneau',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='creneau.creneau', verbose_name='créneau'),
            preserve_default=False,
        ),
    ]
