# Generated by Django 3.1.6 on 2021-03-21 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0003_auto_20210216_1534'),
        ('client', '0012_auto_20210309_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='slug',
        ),
        migrations.AlterField(
            model_name='client',
            name='adress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='creneau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='creneau.creneau', verbose_name='créneau'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=22, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='adress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='phone',
            field=models.CharField(blank=True, max_length=22, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='state',
            field=models.CharField(choices=[('A', 'Active'), ('S', 'Suspendue'), ('N', 'Non active')], default='A', max_length=3, verbose_name='Etat'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='adress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='phone',
            field=models.CharField(blank=True, max_length=22, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='state',
            field=models.CharField(choices=[('A', 'Active'), ('S', 'Suspendue'), ('N', 'Non active')], default='A', max_length=3, verbose_name='Etat'),
        ),
    ]
