# Generated by Django 3.1.6 on 2021-03-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_auto_20210321_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='heures_done',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='pay_per_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
