# Generated by Django 3.1.6 on 2021-03-21 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_maladie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maladie',
            name='Client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maladies', to='client.client'),
        ),
    ]
