# Generated by Django 3.1.6 on 2021-03-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_auto_20210321_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='maladies',
            field=models.ManyToManyField(to='client.Maladie'),
        ),
    ]
