# Generated by Django 3.1.6 on 2021-03-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_coach_maladies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='maladies',
        ),
    ]
