# Generated by Django 3.1.6 on 2021-03-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0003_auto_20210216_1534'),
        ('client', '0019_remove_coach_maladies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='creneau',
        ),
        migrations.AddField(
            model_name='client',
            name='creneau',
            field=models.ManyToManyField(to='creneau.Creneau', verbose_name='créneau'),
        ),
    ]
