# Generated by Django 3.1.6 on 2021-03-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0003_auto_20210325_1044'),
        ('client', '0020_auto_20210323_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='abonnement',
            field=models.ManyToManyField(to='abonnement.Abonnement'),
        ),
    ]
