# Generated by Django 3.1.6 on 2021-03-25 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_client_abonnement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='abonnement',
        ),
    ]
