# Generated by Django 3.1.6 on 2021-03-25 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0003_auto_20210216_1534'),
        ('client', '0022_remove_client_abonnement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='creneau',
        ),
        migrations.AddField(
            model_name='client',
            name='creneau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creneau.creneau', verbose_name='créneau'),
        ),
    ]
