# Generated by Django 3.1.6 on 2021-03-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0024_auto_20210325_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='creneau',
        ),
    ]
