# Generated by Django 3.1.6 on 2021-03-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_remove_client_creneau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='creneau',
        ),
    ]
