# Generated by Django 3.1.6 on 2021-04-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0026_remove_coach_creneau'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='picture',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
