# Generated by Django 3.1.6 on 2021-04-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0027_client_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nationalité'),
        ),
        migrations.AlterField(
            model_name='client',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
