# Generated by Django 3.1.6 on 2021-04-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0028_auto_20210415_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='dette',
            new_name='reste',
        ),
    ]
