# Generated by Django 3.1.6 on 2021-04-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0029_auto_20210419_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='reste',
            new_name='salaire',
        ),
    ]
