# Generated by Django 3.1.6 on 2021-04-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0030_auto_20210419_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='salaire',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
