# Generated by Django 3.1.6 on 2021-04-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0031_auto_20210419_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='pay_per_hour',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
