# Generated by Django 3.1.6 on 2021-04-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0032_auto_20210419_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='avance',
        ),
    ]
