# Generated by Django 3.1.6 on 2021-05-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0033_remove_personnel_avance'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='faux_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
