# Generated by Django 3.1.6 on 2021-05-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0035_remove_client_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
    ]
