# Generated by Django 3.1.6 on 2021-05-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0036_auto_20210503_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_added',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
