# Generated by Django 3.1.6 on 2021-05-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0037_auto_20210503_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dette',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
