# Generated by Django 3.1.6 on 2021-05-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0038_auto_20210503_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='faux_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
