# Generated by Django 3.1.6 on 2021-05-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0039_auto_20210503_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dette',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
