# Generated by Django 3.1.6 on 2021-05-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0040_auto_20210503_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Date de naissance'),
        ),
    ]
