# Generated by Django 3.1.6 on 2021-02-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Moantant')),
                ('inscription_date', models.DateField(auto_now_add=True, verbose_name="date d'ajout")),
                ('quantity', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='remarque')),
            ],
        ),
    ]
