# Generated by Django 3.1.6 on 2021-02-21 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salle_activite', '0004_remove_activity_creneau'),
        ('materiel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='salle_activite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salle_activite.salle', verbose_name="salle d'activité"),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nom'),
        ),
    ]
