# Generated by Django 3.1.6 on 2021-02-16 14:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0004_auto_20210216_1534'),
        ('abonnement', '0001_initial'),
        ('assurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_creation', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Autre',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction.transaction')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
            bases=('transaction.transaction',),
        ),
        migrations.CreateModel(
            name='RemunerationProf',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction.transaction')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rem_coachs', to='client.coach')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
            bases=('transaction.transaction',),
        ),
        migrations.CreateModel(
            name='Remuneration',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction.transaction')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rem_personnels', to='client.personnel')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
            bases=('transaction.transaction',),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction.transaction')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='abonnement.abonnement')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
            bases=('transaction.transaction',),
        ),
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction.transaction')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assurances', to='assurance.assurance')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
            bases=('transaction.transaction',),
        ),
    ]
