# Generated by Django 3.1.6 on 2021-02-21 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20210218_1603'),
        ('abonnement', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assurance',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='client.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiement',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='client.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='abonnement.abonnement', verbose_name='paiement abonnement'),
        ),
    ]
