# Generated by Django 3.1.6 on 2021-02-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0001_initial'),
        ('transaction', '0002_auto_20210221_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remuneration',
            old_name='type',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='remunerationprof',
            old_name='type',
            new_name='coach',
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='abonnement.abonnement', verbose_name='abonnement'),
        ),
    ]
