# Generated by Django 3.1.6 on 2021-04-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_remove_paiement_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-last_modified']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-last_modified']},
        ),
        migrations.AlterField(
            model_name='autre',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
