# Generated by Django 3.1.6 on 2021-04-24 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0033_remove_personnel_avance'),
        ('transaction', '0006_auto_20210420_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='client.client'),
        ),
    ]
