# Generated by Django 3.1.6 on 2021-02-16 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0002_creneau_planning'),
        ('salle_activite', '0002_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='creneau',
            field=models.ManyToManyField(to='creneau.Creneau', verbose_name='créneau'),
        ),
        migrations.AddField(
            model_name='activity',
            name='salle',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='salle_activite.salle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salle',
            name='name',
            field=models.CharField(max_length=50, verbose_name="nom de la salle d'activité"),
        ),
    ]
