# Generated by Django 3.1.6 on 2021-02-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salle_activite', '0003_auto_20210216_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='creneau',
        ),
    ]
