# Generated by Django 3.1.6 on 2021-04-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salle_activite', '0004_remove_activity_creneau'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='color',
            field=models.CharField(default='#233774', max_length=50),
        ),
    ]
