# Generated by Django 3.1.6 on 2021-02-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('day', models.CharField(choices=[('SA', 'Samedi'), ('DI', 'Dimanche'), ('LU', 'Lundi'), ('MA', 'Mardi'), ('ME', 'Mercredi'), ('JE', 'Jeudi'), ('VE', 'Vendredi')], default='SA', max_length=2, verbose_name='Jour')),
                ('hour_start', models.TimeField()),
                ('hour_finish', models.TimeField()),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
    ]
