# Generated by Django 3.1.6 on 2021-02-16 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        ('creneau', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='planning',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='planning.planning'),
            preserve_default=False,
        ),
    ]
