# Generated by Django 3.1.6 on 2021-02-16 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salle_activite', '0004_remove_activity_creneau'),
        ('creneau', '0002_creneau_planning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creneau',
            name='name',
        ),
        migrations.AddField(
            model_name='creneau',
            name='activity',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='salle_activite.activity', verbose_name="salle d'activité"),
            preserve_default=False,
        ),
    ]
