# Generated by Django 3.1.6 on 2021-03-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salle_activite', '0004_remove_activity_creneau'),
        ('creneau', '0003_auto_20210216_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creneau',
            name='activity',
        ),
        migrations.AddField(
            model_name='creneau',
            name='activity',
            field=models.ManyToManyField(to='salle_activite.Activity', verbose_name='activities'),
        ),
    ]
