# Generated by Django 3.1.6 on 2021-03-28 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salle_activite', '0004_remove_activity_creneau'),
        ('creneau', '0004_auto_20210328_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creneau',
            name='activity',
        ),
        migrations.AddField(
            model_name='creneau',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='salle_activite.activity', verbose_name='activities'),
            preserve_default=False,
        ),
    ]
