# Generated by Django 3.1.6 on 2021-03-29 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salle_activite', '0004_remove_activity_creneau'),
        ('creneau', '0005_auto_20210328_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salle_activite.activity', verbose_name='activities'),
        ),
    ]
