# Generated by Django 3.1.6 on 2021-04-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0027_client_picture'),
        ('creneau', '0008_remove_creneau_abonnements'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='coach',
            field=models.ManyToManyField(to='client.Coach'),
        ),
    ]
