# Generated by Django 3.1.6 on 2021-04-06 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0027_client_picture'),
        ('creneau', '0009_creneau_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creneau',
            name='coach',
        ),
        migrations.AddField(
            model_name='creneau',
            name='coach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.coach', verbose_name='activities'),
            preserve_default=False,
        ),
    ]
