# Generated by Django 3.1.6 on 2021-04-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0010_auto_20210406_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creneau',
            options={'ordering': ['hour_start']},
        ),
    ]
