# Generated by Django 3.1.6 on 2021-04-09 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0027_client_picture'),
        ('creneau', '0013_auto_20210407_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.coach'),
        ),
    ]
