# Generated by Django 3.1.6 on 2021-04-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0014_auto_20210409_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creneau',
            name='actif',
        ),
    ]
