# Generated by Django 3.1.6 on 2021-04-19 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0028_auto_20210415_1017'),
        ('creneau', '0015_remove_creneau_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='client.coach'),
        ),
    ]
