# Generated by Django 3.1.6 on 2021-03-23 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0003_auto_20210216_1534'),
        ('client', '0019_remove_coach_maladies'),
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AddField(
            model_name='presence',
            name='creneau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creneau.creneau'),
        ),
    ]
