# Generated by Django 3.1.6 on 2021-03-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0002_auto_20210323_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='is_in_list',
            field=models.BooleanField(default=True),
        ),
    ]
