# Generated by Django 3.1.6 on 2021-03-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0003_presence_is_in_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='is_in_salle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='presence',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='presence',
            name='hour_entree',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='presence',
            name='hour_sortie',
            field=models.TimeField(blank=True),
        ),
    ]
