# Generated by Django 3.1.6 on 2021-03-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0004_auto_20210323_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='hour_sortie',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
