# Generated by Django 3.1.6 on 2021-03-28 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0004_auto_20210328_1600'),
        ('client', '0024_auto_20210325_1424'),
        ('presence', '0005_auto_20210324_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='client.client'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='creneau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presenses', to='creneau.creneau'),
        ),
    ]
