# Generated by Django 3.1.6 on 2021-03-30 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0026_remove_coach_creneau'),
        ('presence', '0007_auto_20210330_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='abonnement',
        ),
        migrations.AddField(
            model_name='presence',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='client.client'),
        ),
    ]
