# Generated by Django 3.1.6 on 2021-03-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0008_auto_20210330_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='hour_entree',
            field=models.TimeField(),
        ),
    ]
