# Generated by Django 3.1.6 on 2021-04-19 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0016_auto_20210419_1244'),
        ('client', '0031_auto_20210419_1420'),
        ('presence', '0009_auto_20210331_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceCoach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('hour_entree', models.TimeField()),
                ('hour_sortie', models.TimeField(blank=True, null=True)),
                ('is_in_salle', models.BooleanField(default=False)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presencesCoach', to='client.coach')),
                ('creneau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presencesCoach', to='creneau.creneau')),
            ],
        ),
    ]
