# Generated by Django 3.1.6 on 2021-04-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0010_presencecoach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presencecoach',
            name='creneau',
        ),
    ]
