# Generated by Django 3.1.6 on 2021-04-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0011_remove_presencecoach_creneau'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
