# Generated by Django 3.1.6 on 2021-05-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0012_presence_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presence',
            options={'ordering': ['-date']},
        ),
    ]
