# Generated by Django 3.1.6 on 2021-03-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='prix'),
        ),
    ]
