# Generated by Django 3.1.6 on 2021-03-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0002_auto_20210322_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonnement',
            name='type',
        ),
        migrations.AddField(
            model_name='abonnement',
            name='presence_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
