# Generated by Django 3.1.6 on 2021-03-25 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_remove_client_abonnement'),
        ('abonnement', '0003_auto_20210325_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abonnement',
            old_name='presence_quantity',
            new_name='number_of_days',
        ),
        migrations.RemoveField(
            model_name='abonnement',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='abonnement',
            name='start_date',
        ),
        migrations.AddField(
            model_name='abonnement',
            name='seances_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AbonnementClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField()),
                ('presence_quantity', models.IntegerField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abonnement_client', to='client.client')),
                ('type_abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement_client', to='abonnement.abonnement')),
            ],
        ),
    ]
