# Generated by Django 3.1.6 on 2021-03-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0004_auto_20210325_1116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AlterField(
            model_name='abonnementclient',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='abonnementclient',
            name='presence_quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
