# Generated by Django 3.1.6 on 2021-03-25 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0005_auto_20210325_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnementclient',
            name='type_abonnement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_abonnement_client', to='abonnement.abonnement'),
        ),
    ]
