# Generated by Django 3.1.6 on 2021-03-29 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salle_activite', '0004_remove_activity_creneau'),
        ('abonnement', '0006_auto_20210325_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='salle_activite.activity'),
            preserve_default=False,
        ),
    ]
