# Generated by Django 3.1.6 on 2021-03-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0005_auto_20210328_1637'),
        ('abonnement', '0007_abonnement_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnementclient',
            name='creneau',
            field=models.ManyToManyField(to='creneau.Creneau', verbose_name='créneau'),
        ),
    ]
