# Generated by Django 3.1.6 on 2021-03-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0006_auto_20210329_1603'),
        ('abonnement', '0008_abonnementclient_creneau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnementclient',
            name='creneau',
            field=models.ManyToManyField(blank=True, null=True, to='creneau.Creneau', verbose_name='créneau'),
        ),
    ]
