# Generated by Django 3.1.6 on 2021-03-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0006_auto_20210329_1603'),
        ('abonnement', '0010_auto_20210329_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnementclient',
            name='creneau',
            field=models.ManyToManyField(blank=True, related_name='creneaux', to='creneau.Creneau', verbose_name='créneau'),
        ),
    ]
