# Generated by Django 3.1.6 on 2021-03-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0011_auto_20210329_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonnementclient',
            name='creneau',
        ),
    ]
