# Generated by Django 3.1.6 on 2021-03-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0008_remove_creneau_abonnements'),
        ('abonnement', '0012_remove_abonnementclient_creneau'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnementclient',
            name='creneaux',
            field=models.ManyToManyField(blank=True, related_name='creneaux', to='creneau.Creneau', verbose_name='créneau'),
        ),
    ]
