# Generated by Django 3.1.6 on 2021-03-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0013_abonnementclient_creneaux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnementclient',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
