# Generated by Django 3.1.6 on 2021-03-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0014_auto_20210330_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnementclient',
            name='presence_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
