# Generated by Django 3.1.6 on 2021-03-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0008_remove_creneau_abonnements'),
        ('abonnement', '0015_auto_20210330_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnementclient',
            name='creneaux',
            field=models.ManyToManyField(blank=True, related_name='abon', to='creneau.Creneau', verbose_name='créneau'),
        ),
    ]
