# Generated by Django 3.1.6 on 2021-03-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creneau', '0008_remove_creneau_abonnements'),
        ('abonnement', '0016_auto_20210330_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnementclient',
            name='creneaux',
            field=models.ManyToManyField(related_name='pizzas', to='creneau.Creneau'),
        ),
    ]
