# Generated by Django 3.1.6 on 2021-04-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salle_activite', '0004_remove_activity_creneau'),
        ('abonnement', '0018_auto_20210330_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonnement',
            name='activity',
        ),
        migrations.AddField(
            model_name='abonnement',
            name='activity',
            field=models.ManyToManyField(to='salle_activite.Activity'),
        ),
    ]
