# Generated by Django 3.1.6 on 2021-04-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0019_auto_20210401_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonnementclient',
            name='type_abonnement',
        ),
        migrations.AddField(
            model_name='abonnementclient',
            name='type_abonnement',
            field=models.ManyToManyField(blank=True, null=True, to='abonnement.Abonnement'),
        ),
    ]
