# Generated by Django 3.1.6 on 2021-04-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0020_auto_20210407_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnementclient',
            name='type_abonnement',
            field=models.ManyToManyField(to='abonnement.Abonnement'),
        ),
    ]
