# Generated by Django 3.1.6 on 2021-04-07 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0021_auto_20210407_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonnementclient',
            name='type_abonnement',
        ),
        migrations.AddField(
            model_name='abonnementclient',
            name='type_abonnement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_abonnement_client', to='abonnement.abonnement'),
            preserve_default=False,
        ),
    ]
