# Generated by Django 3.1.6 on 2021-04-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salle_activite', '0005_activity_color'),
        ('abonnement', '0022_auto_20210407_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='activity',
            field=models.ManyToManyField(related_name='activities', to='salle_activite.Activity'),
        ),
    ]
