# Generated by Django 3.1.6 on 2021-05-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0023_auto_20210407_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnementclient',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
