# Generated by Django 3.1.6 on 2021-05-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0024_abonnementclient_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='systeme_cochage',
            field=models.BooleanField(default=False),
        ),
    ]
